# Generated by Django 5.1.1 on 2024-10-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capitao', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
